name: Compile and Run C Program

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  compile-and-run:
    runs-on: [self-hosted, Linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile main.c
        run: make

      - name: Run compiled program
        run: ./target/file_printer
