name: Compile and Run C Program

on:
  workflow_dispatch:
  pull_request:
    branches:
      - x64-test
    types:
      - opened
      - synchronize

jobs:

  compile-and-run-x64:
    if: github.base_ref == 'x64-test'
    runs-on: [self-hosted, Linux, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile main.c
        run: make

      - name: Run compiled program
        run: ./target/file_printer
